[package]
name = "advance_data_base_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.4", features = ["mysql", "64-column-tables", "bigdecimal"] }
leptos = { version = "0.2.5", features = ["stable"] }
plotters = "0.3"
