// @generated automatically by Diesel CLI.
#![recursion_limit = "256"]
diesel::table! {
    accidentes_2018 (id) {
        id -> Integer,
        COBERTURA -> Varchar,
        ID_ENTIDAD -> Varchar,
        ID_MUNICIPIO -> Varchar,
        ANIO -> Varchar,
        MES -> Integer,
        ID_HORA -> Integer,
        ID_MINUTO -> Integer,
        ID_DIA -> Integer,
        DIASEMANA -> Varchar,
        URBANA -> Varchar,
        SUBURBANA -> Varchar,
        TIPACCID -> Varchar,
        AUTOMOVIL -> Varchar,
        CAMPASAJ -> Integer,
        MICROBUS -> Integer,
        PASCAMION -> Integer,
        OMNIBUS -> Integer,
        TRANVIA -> Integer,
        CAMIONETA -> Integer,
        CAMION -> Integer,
        TRACTOR -> Integer,
        FERROCARRI -> Nullable<Integer>,
        MOTOCICLET -> Nullable<Integer>,
        BICICLETA -> Nullable<Integer>,
        OTROVEHIC -> Nullable<Integer>,
        CAUSAACCI -> Nullable<Varchar>,
        CAPAROD -> Nullable<Varchar>,
        SEXO -> Nullable<Varchar>,
        ALIENTO -> Nullable<Varchar>,
        CINTURON -> Nullable<Varchar>,
        ID_EDAD -> Nullable<Varchar>,
        CONDMUERTO -> Nullable<Varchar>,
        CONDHERIDO -> Nullable<Varchar>,
        PASAMUERTO -> Nullable<Varchar>,
        PASAHERIDO -> Nullable<Varchar>,
        PEATMUERTO -> Nullable<Varchar>,
        PEATHERIDO -> Nullable<Varchar>,
        CICLMUERTO -> Nullable<Varchar>,
        CICLHERIDO -> Nullable<Varchar>,
        OTROMUERTO -> Nullable<Varchar>,
        OTROHERIDO -> Nullable<Varchar>,
        NEMUERTO -> Nullable<Varchar>,
        NEHERIDO -> Nullable<Varchar>,
        CLASACC -> Nullable<Varchar>,
        ESTATUS -> Nullable<Varchar>,
    }
}

diesel::table! {
    accidentes_2019 (id) {
        id -> Integer,
        COBERTURA -> Varchar,
        ID_ENTIDAD -> Varchar,
        ID_MUNICIPIO -> Varchar,
        ANIO -> Varchar,
        MES -> Integer,
        ID_HORA -> Integer,
        ID_MINUTO -> Integer,
        ID_DIA -> Integer,
        DIASEMANA -> Varchar,
        URBANA -> Varchar,
        SUBURBANA -> Varchar,
        TIPACCID -> Varchar,
        AUTOMOVIL -> Varchar,
        CAMPASAJ -> Integer,
        MICROBUS -> Integer,
        PASCAMION -> Integer,
        OMNIBUS -> Integer,
        TRANVIA -> Integer,
        CAMIONETA -> Integer,
        CAMION -> Integer,
        TRACTOR -> Integer,
        FERROCARRI -> Nullable<Integer>,
        MOTOCICLET -> Nullable<Integer>,
        BICICLETA -> Nullable<Integer>,
        OTROVEHIC -> Nullable<Integer>,
        CAUSAACCI -> Nullable<Varchar>,
        CAPAROD -> Nullable<Varchar>,
        SEXO -> Nullable<Varchar>,
        ALIENTO -> Nullable<Varchar>,
        CINTURON -> Nullable<Varchar>,
        ID_EDAD -> Nullable<Varchar>,
        CONDMUERTO -> Nullable<Varchar>,
        CONDHERIDO -> Nullable<Varchar>,
        PASAMUERTO -> Nullable<Varchar>,
        PASAHERIDO -> Nullable<Varchar>,
        PEATMUERTO -> Nullable<Varchar>,
        PEATHERIDO -> Nullable<Varchar>,
        CICLMUERTO -> Nullable<Varchar>,
        CICLHERIDO -> Nullable<Varchar>,
        OTROMUERTO -> Nullable<Varchar>,
        OTROHERIDO -> Nullable<Varchar>,
        NEMUERTO -> Nullable<Varchar>,
        NEHERIDO -> Nullable<Varchar>,
        CLASACC -> Nullable<Varchar>,
        ESTATUS -> Nullable<Varchar>,
    }
}

diesel::allow_tables_to_appear_in_same_query!(accidentes_2018, accidentes_2019,);
